# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
   codecov: codecov/codecov@3.2.3

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - validate-code
      - unit-test:
          requires:
            - validate-code
      - functional-test:
          requires:
            - validate-code
      - integration-test:
          requires:
            - validate-code
      - build_xcframework_and_app:
          requires:
            - validate-code

jobs:
  
  working_directory: ~/project

  install_dependencies: &install_dependencies
    steps:
      - checkout

      # restore pods related caches
      - restore_cache:
          keys:
            - 1-gems-{{ checksum "Gemfile.lock" }}

      # make sure we're on the right version of cocoapods
      - run:
          name: Verify Cocoapods Version
          command: bundle check || bundle install --path vendor/bundle

      # save cocoapods version gem data
      - save_cache:
          key: 1-gems-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle

      # restore pods related caches
      - restore_cache:
          keys:
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Podfile.lock" }}
            - cocoapods-cache-v1-{{ arch }}-{{ .Branch }}
            - cocoapods-cache-v1

      # install CocoaPods - using default CocoaPods version, not the bundle
      - run:
          name: Repo Update & Install CocoaPods
          command: make ci-pod-install

      # save pods related files
      - save_cache:
          name: Saving CocoaPods Cache
          key: cocoapods-cache-v1-{{ arch }}-{{ .Branch }}-{{ checksum "Podfile.lock" }}
          paths:
            - ./Pods

  validate-code:
    macos:
      xcode: 13.4.0 # Specify the Xcode version to use

    steps:
      - checkout

      <<: *install_depencies

      - run:
          name: Lint Source Code
          command: make lint
    
  unit-test:
    macos:
      xcode: 13.4.0 # Specify the Xcode version to use

    steps:
      - checkout

      <<: *install_depencies

      # pre-start the simulator to prevent timeouts
      - run:
          name: Pre-start Simulator
          command: xcrun instruments -w "iPhone 8 (13.5) [" || true

      - run:
          name: Run iOS Unit Tests
          command: make unit-test-ios

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for iOS Unit Tests
          xtra_args: -c -v --xc --xp iosunittestresults.xcresult

      - run:
          name: Pre-start tvOS Simulator
          command: xcrun instruments -w "Apple TV (15.0) [" || true

      - run:
          name: Run tvOS Unit Tests
          command: make unit-test-tvos

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for tvOS Unit Tests
          xtra_args: -c -v --xc --xp tvosunittestresults.xcresult

  functional-test:
    macos:
      xcode: 13.4.0 # Specify the Xcode version to use

    steps:
      - checkout
      
      <<: *install_depencies

      # pre-start the simulator to prevent timeouts
      - run:
          name: Pre-start Simulator
          command: xcrun instruments -w "iPhone 8 (13.5) [" || true

      - run:
          name: Run iOS Functional Tests
          command: make functional-test-ios

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for iOS Functional Tests
          xtra_args: -c -v --xc --xp iosfunctionaltestresults.xcresult

      - run:
          name: Pre-start tvOS Simulator
          command: xcrun instruments -w "Apple TV (15.0) [" || true

      - run:
          name: Run tvOS Functional Tests 
          command: make functional-test-tvos

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for tvOS Functional Tests
          xtra_args: -c -v --xc --xp tvosfunctionaltestresults.xcresult

  integration-test:
    macos:
      xcode: 13.4.0 # Specify the Xcode version to use
    
    steps:
      - checkout

      <<: *install_depencies

      # pre-start the simulator to prevent timeouts
      - run:
          name: Pre-start Simulator
          command: xcrun instruments -w "iPhone 8 (13.5) [" || true

      - run:
          name: Run iOS Integration Tests
          command: make integration-test-ios

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for iOS Integration Tests
          xtra_args: -c -v --xc --xp iosintegrationtestresults.xcresult

      - run:
          name: Pre-start tvOS Simulator
          command: xcrun instruments -w "Apple TV (15.0) [" || true

      - run:
          name: Run tvOS Integration Tests
          command: make integration-test-tvos

      # Code coverage upload using Codecov
      # See options explanation here: https://docs.codecov.com/docs/codecov-uploader
      - codecov/upload:
          upload_name: Coverage Report for tvOS Integration Tests
          xtra_args: -c -v --xc --xp tvosintegrationtestresults.xcresult

  build_xcframework_and_app:
    macos:
      xcode: 13.4.0 # Specify the Xcode version to use
    
    steps:
      - checkout
      # verify XCFramework archive builds
      - run:
          name: Build XCFramework
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              make archive
            fi

      # verify test app builds
      - run:
          name: Build Test App
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              make build-app
            fi
